version: "3.8"

networks:
  main-network:
    driver: bridge

services:
  kafka-broker:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka-broker
    container_name: kafka-broker
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-broker:9092,CONTROLLER://kafka-broker:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - main-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "8089:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9092
    depends_on:
      - kafka-broker
    networks:
      - main-network

  telemetry-service-database:
    image: postgres:16
    container_name: telemetry-service-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${TELEMETRY_DB_NAME}
      POSTGRES_USER: ${TELEMETRY_DB_USER}
      POSTGRES_PASSWORD: ${TELEMETRY_DB_PASSWORD}
    volumes:
        - telemetry-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TELEMETRY_DB_USER} -d ${TELEMETRY_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - main-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    depends_on:
      - telemetry-service-database
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - main-network

  simulator-service:
    build:
      context: ./services/simulator-service
    ports:
      - "8081:8080"
    networks:
      - main-network

  gateway-service:
    build:
      context: ./services/gateway-service
    ports:
      - "8082:8080"
    networks:
      - main-network

  telemetry-service:
    build:
      context: ./services/telemetry-service
    ports:
      - "8083:8080"
    depends_on:
      telemetry-service-database:
        condition: service_healthy
    networks:
      - main-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/var/lib/prometheus
    depends_on:
      - simulator-service
    networks:
      - main-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - main-network

volumes:
  pgadmin-data:
  kafka-data:
  telemetry-db-data:
  grafana-data:
  prometheus-data:
