server:
  port: 8080

spring:
  application:
    name: simulator-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

gateway-service:
  telemetry:
    destination: "ws://gateway-service:8080/ws"