server:
  port: 8080

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  application:
    name: telemetry-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-broker:9092}
    properties:
      schema:
        registry:
          url: ${SCHEMA_REGISTRY_URL}
    topic:
      telemetry: "telemetry-topic"
    consumer:
      group-id: "telemetry-service"
      properties:
        specific:
          protobuf:
            value:
              type: com.yyrobotics.contracts.proto.RoverTelemetry

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always