plugins {
    id 'java'
    id 'com.google.protobuf' version '0.9.4'
}

group = 'com.yyrobotics'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.protobuf:protobuf-java:4.29.0'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:4.29.0'
    }
}

sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}